linters:
  enable:
    - gofmt
    - errorlint
    - gosec
    - misspell
    - sqlclosecheck
linters-settings:
  gofmt:
    simplify: true
  misspell:
    locale: US
  gosec:
    excludes:
      - G404
run:
  timeout: 10m
  skip-dirs:
    - tmp