name: go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: lint
        run: make lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: test
        run: make test
      - name: cover
        run: make cover
  vet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: vet
        run: make vet
      - name: trufflehog
        run: make trufflehog
